export const copy = {
  appName: "测试用例平台",
  appSubtitle: "TestOps",
  projects: "项目",
  newProject: "新建项目",
  upload: "上传资料",
  testCases: "用例预览",
  createProject: "创建项目",
  createProjectHint: "为要生成和评审用例的产品域创建一个工作区。",
  projectCreated: "项目创建成功。",
  projectArchivedToast: "项目已归档。",
  projectRestoredToast: "项目已恢复。",
  projectName: "项目名称",
  projectCode: "项目代号",
  description: "项目描述",
  noProjects: "暂无项目",
  noProjectsHint: "点击「新建项目」开始，可上传资料生成测试用例，或导入 Markdown 用例文件。",
  documents: "文档",
  drafts: "草稿",
  published: "已发布",
  stepUpload: "上传资料",
  stepGenerate: "生成用例",
  stepPreview: "预览评审",
  uploadTitle: "上传需求与接口资料",
  uploadHint: "无需逐条编写用例。上传资料后，系统将生成用例草稿。",
  generate: "生成测试用例",
  generating: "正在生成用例…",
  addDocument: "添加文档",
  selectAll: "全选",
  clearSelection: "清空选择",
  noDocuments: "暂无文档",
  noDocumentsHint: "上传 PRD、业务规则、补充资料、Swagger 或 Figma 链接后即可生成用例。",
  generationComplete: "生成完成",
  generationCompleteHint: "请在下方预览草稿，修改措辞后批准并发布。",
  noTestCases: "暂无用例",
  noTestCasesHint: "请回到工作台：上传资料生成测试用例，或导入 Markdown 用例文件。",
  backToUpload: "返回工作台",
  searchPlaceholder: "搜索用例标题…",
  filterAll: "全部状态",
  save: "保存修改",
  saving: "保存中…",
  saved: "已保存",
  approve: "批准",
  requestChanges: "退回修改",
  reject: "驳回",
  publish: "发布用例",
  publishHint: "请先点击「批准」，通过后再发布给下游使用。",
  publishReady: "用例已批准，可以发布。",
  publishedLocked: "用例已发布，内容已锁定。",
  reviewComment: "评审意见",
  reviewHistory: "评审记录",
  stepColumn: "操作步骤",
  expectedColumn: "预期结果",
  module: "模块",
  feature: "功能点",
  priority: "优先级",
  preconditions: "前置条件",
  modeGenerate: "上传资料生成",
  modeImport: "导入用例",
  modeGenerateHint: "上传 PRD、业务规则、补充资料、Swagger 或 Figma 资料，由系统生成用例草稿。",
  modeImportHint: "已有用例文件时，可直接导入 Markdown 用例文件，无需先生成用例草稿。",
  importTitle: "上传用例文件",
  importHint: "导入后将进入预览、评审与发布流程。",
  importEmptyTitle: "尚未选择文件",
  importEmptyHint: "可下载模板，按格式填写后上传 Markdown 文件。",
  downloadTemplate: "下载模板",
  importAction: "导入用例",
  importing: "正在导入用例…",
  importComplete: "导入完成",
  importCompleteHint: "用例已写入项目，可在下方预览并继续评审。",
  chooseFile: "选择文件",
  noFileChosen: "未选择文件",
  rechooseFile: "重新选择",
  composeTitle: "在线编写用例",
  composeHint: "按 UI 自动化结构填写步骤、定位信息与测试数据，保存后可用于生成脚本。",
  composeToolbarHint: "步骤表每一行对应一个可执行 UI 操作，定位提示支持多个候选选择器。",
  createTestCase: "创建用例",
  newTestCase: "在线编写用例",
  environmentSection: "运行环境",
  framework: "自动化框架",
  browser: "浏览器",
  baseUrl: "基础 URL",
  entryPath: "入口路径",
  entryReadySelector: "就绪选择器",
  viewport: "视口",
  testData: "测试数据",
  uiStepsSection: "UI 操作步骤",
  actionColumn: "动作",
  targetColumn: "目标元素",
  locatorColumn: "定位提示",
  valueColumn: "输入值",
  assertionColumn: "步骤断言",
  expectedSummary: "用例级预期",
  automationNotes: "AI 生成说明",
  teardown: "清理 / 收尾",
  tags: "标签",
  importTemplateHint: "模板采用 Markdown 结构，包含模块、步骤与预期结果；多条用例用 --- 分隔。",
  composeOrImport: "在线编写用例",
  pageErrorTitle: "页面加载失败",
  pageErrorHint: "请确认后端 API 已启动，或稍后重试。",
  retry: "重试",
  backHome: "返回首页",
  notFoundTitle: "页面不存在",
  notFoundHint: "链接可能已失效，或项目已被删除。",
  loading: "加载中…",
  apiUnavailable: "无法连接 TestOps API，请先启动后端服务（端口 8000）。",
  shellCopy: "上传需求资料，生成草稿，完成评审与发布。",
  navLabel: "导航",
  projectNavLabel: "项目导航",
  workspaceEyebrow: "项目工作台",
  testCasePreviewEyebrow: "测试用例库",
  testCasePreviewHint: "筛选、查看并编辑生成的用例草稿，完成后批准并发布。",
  testCaseDetailEyebrow: "用例详情",
  projectDirectoryEyebrow: "项目目录",
  projectDirectoryTitle: "项目工作区",
  projectDirectoryHint: "创建项目、上传需求资料，生成并评审测试用例。",
  apiUnavailableTitle: "API 不可用",
  projectCount: (count: number) => `共 ${count} 个项目`,
  noDescription: "暂无项目描述",
  nextStepEyebrow: "待进入预览",
  nextStepTitle: (count: number) => `${count} 条用例草稿待处理`,
  nextStepHint: "进入预览页编辑步骤、完成批准并发布。",
  defaultProjectHint: "可上传资料生成测试用例，或导入已有 Markdown 用例文件。",
  backToList: "返回列表",
  closeModal: "关闭",
  confirmReject: "确定驳回该用例？驳回后需重新修改并批准。",
  confirmPublish: "确定发布该用例？发布后将锁定内容，下游系统可拉取。",
  noReviewHistory: "暂无评审记录。",
  reviewCommentPlaceholder: "可选：说明修改建议或批准理由",
  importPreviewSummary: (count: number) => `已识别 ${count} 条用例，导入后将进入预览与评审流程。`,
  importProgress: (count: number) => `正在导入 ${count} 条用例，请稍候…`,
  generateProgress: (count: number) => `正在根据 ${count} 份文档生成用例草稿，请稍候…`,
  listCount: (shown: number, total: number) => `显示 ${shown} / ${total} 条`,
  noMatchingCases: "没有匹配的用例",
  adjustFiltersHint: "试试调整搜索词或状态筛选。",
  stepCount: (count: number) => `${count} 步`,
  documentCountLabel: (count: number) => `${count} 份文档`,
  generateDone: "已完成",
  generatePending: "待执行",
  publishedSummary: (count: number) => ` · ${count} 已发布`,
  flowApprove: "1. 批准",
  flowPublish: "2. 发布",
  addItem: "+ 添加",
  deleteItem: "删除",
  emptyContent: "暂无内容",
  uploadStepEyebrow: "步骤 1",
  uploadedEyebrow: "已上传",
  documentLibraryTitle: (count: number) => `${count} 份文档`,
  documentNameLabel: "文档名称",
  sourceUrlLabel: "来源 URL",
  chooseFileLabel: "选择文件",
  skipGenerateEyebrow: "导入现有用例",
  importFileLabel: "用例文件（Markdown）",
  importedBatch: (count: number) => `（本次导入 ${count} 条）`,
  internalStorage: "内部存储",
  fillDocumentName: "请填写文档名称。",
  fillValidUrl: "请粘贴有效的 URL。",
  chooseUploadFile: "请选择要上传的文件。",
  uploadDocumentFailed: "添加文档失败。",
  selectOneDocument: "请至少选择一份文档。",
  generateFailed: "生成失败。",
  documentAdded: (name: string) => `已添加「${name}」，可继续添加或生成用例。`,
  createFailed: "创建失败，请确认后端 API 已启动（端口 8000）。",
  reviewActionFailed: "评审操作失败。",
  parseImportFailed: "无法解析用例文件。",
  chooseValidImportFile: "请先选择有效的 Markdown 用例文件。",
  importFailed: "导入失败。",
  searchLabel: "搜索",
  statusFilterLabel: "状态筛选",
  uiAutomationEyebrow: "UI 自动化",
  documentTypeTabLabel: "文档类型",
  workspaceModeTabLabel: "创建方式",
  projectListLabel: "项目列表",
  archiveProject: "归档项目",
  restoreProject: "恢复项目",
  cancelAction: "取消",
  activeProjects: "进行中项目",
  archivedProjects: "已归档项目",
  projectArchived: "项目已归档",
  projectArchivedHint: "该项目已归档，可继续查看历史数据。如需继续操作，请先恢复项目。",
  archivedProjectReadonlyHint: "归档项目仅支持查看、恢复或删除，恢复后才能继续主链路。",
  archiveProjectConfirm: "归档后项目将从默认列表隐藏，但不会删除已有数据。",
  archiveProjectImpact: "历史文档、用例、生成任务和自动化计划会继续保留，只会从默认项目列表移除。",
  confirmArchiveProject: "确认归档",
  restoreProjectConfirm: "恢复后项目将重新出现在默认列表，并可继续使用。",
  restoreProjectImpact: "恢复后，项目将重新回到进行中项目列表，并恢复文档、用例和计划的常规操作入口。",
  confirmRestoreProject: "确认恢复",
  archivedProjectActionHint: "项目已归档，请先恢复后再继续操作。",
  deleteProject: "删除项目",
  deleteProjectConfirm: "删除后项目文档、Skills、生成任务、用例和自动化数据将不可恢复。",
  deleteProjectImpact: "为避免误删，只有已归档项目可以删除。若只是暂停使用，请保留归档状态。",
  confirmDeleteProject: "确认删除",
  projectDeletedToast: "项目已删除。",
  deleteProjectFailed: "删除项目失败，请稍后再试。",
  updateProjectStatusFailed: "项目状态更新失败，请稍后再试。",
} as const;

export const sourceModeLabels: Record<string, string> = {
  upload: "本地上传",
  url: "链接地址",
  external_link: "外部链接",
};

export const priorityLabels: Record<string, string> = {
  high: "高",
  medium: "中",
  low: "低",
};

export const caseTypeLabels: Record<string, string> = {
  functional: "功能",
  ui_automation: "UI 自动化",
  regression: "回归",
  smoke: "冒烟",
  negative: "异常",
};

export function labelPriority(value: string): string {
  return priorityLabels[value.toLowerCase()] ?? value;
}

export function labelSourceMode(value: string): string {
  return sourceModeLabels[value] ?? value;
}

export function labelCaseType(value: string): string {
  return caseTypeLabels[value.toLowerCase()] ?? value;
}

export const statusLabels: Record<string, string> = {
  draft: "草稿",
  needs_update: "待修改",
  approved: "已批准",
  published: "已发布",
  rejected: "已驳回",
  queued: "排队中",
  running: "生成中",
  succeeded: "已成功",
  failed: "失败",
};

export const documentTypeLabels: Record<string, string> = {
  prd: "PRD",
  business_rule: "业务规则",
  supplement: "补充资料",
  swagger: "Swagger",
  figma: "Figma",
};

export const reviewActionLabels: Record<string, string> = {
  comment: "评论",
  request_change: "退回修改",
  approve: "批准",
  reject: "驳回",
  publish: "发布",
};
